package salve.core

import org.junit.Assert.*
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.io.File
import java.nio.file.Files

class GradleSandboxTestExecutorTest {
    private fun withWrapper(body: String, test: (File) -> Unit) {
        assumeTrue(File("/bin/sh").isFile)
        val workspace = Files.createTempDirectory("salve-process-result").toFile()
        try {
            val wrapper = File(workspace, "gradlew")
            wrapper.writeText("#!/bin/sh\n$body\n")
            assertTrue(wrapper.setExecutable(true))
            test(workspace)
        } finally {
            workspace.deleteRecursively()
        }
    }

    @Test fun failingProcessNeverReportsSuccess() = withWrapper("exit 7") { root ->
        val executor = GradleSandboxTestExecutor(root, 1_000, true, null)
        val result = executor.run(ValidationSandboxTest.suite(ValidationSandboxTest.code()), "Example")
        assertTrue(result.wasAttempted())
        assertFalse(result.wasSuccessful())
        assertTrue(result.steps.any { it.contains("FAIL") })
        assertFalse(File(root, "app/src/test/java/com/salve/sandbox/autogenerated/ExampleTestHarness.java").exists())
    }

    @Test fun successfulSuiteUsesClassNameAndDoesNotClaimCandidateWasTested() = withWrapper(
        "test -f app/src/test/java/com/salve/sandbox/autogenerated/ExampleTestHarness.java || exit 9\nexit 0"
    ) { root ->
        val result = GradleSandboxTestExecutor(root, 1_000, true, null)
            .run(ValidationSandboxTest.suite(ValidationSandboxTest.code()), "Example")
        assertTrue(result.wasSuccessful())
        assertTrue(result.summary.contains("parche candidato no se aplica"))
    }

    @Test fun unavailableExecutorDoesNotInventAnExecution() {
        val result = GradleSandboxTestExecutor(null, 1_000, false, null).run(null, "Example")
        assertFalse(result.wasAttempted())
        assertFalse(result.wasSuccessful())
    }

    @Test fun processLaunchFailureIsNotReportedAsExecuted() = withWrapper("exit 0") { root ->
        assertTrue(File(root, "gradlew").setExecutable(false, false))
        val result = GradleSandboxTestExecutor(root, 1_000, true, null)
            .run(ValidationSandboxTest.suite(ValidationSandboxTest.code()), "Example")
        assertFalse(result.wasAttempted())
        assertFalse(result.wasSuccessful())
        assertTrue(result.summary.contains("no llegó a iniciar"))
    }
}
