package salve.core;

import org.junit.Test;
import java.lang.reflect.Constructor;
import java.util.Collections;
import static org.junit.Assert.*;

public class ValidationSandboxTest {
    static AutoTestGenerator.GeneratedTestSuite suite(String code) throws Exception {
        Constructor<AutoTestGenerator.GeneratedTestSuite> constructor =
                AutoTestGenerator.GeneratedTestSuite.class.getDeclaredConstructor(
                        String.class, String.class, String.class, boolean.class);
        constructor.setAccessible(true);
        return constructor.newInstance("Example", code, "firstMethod", true);
    }

    static String code() {
        return "package com.salve.sandbox.autogenerated; public class ExampleTestHarness {\n"
                + "@Test public void firstMethod() { assertTrue(Example.ok()); }\n"
                + "@Test public void secondMethod() { assertFalse(Example.bad()); }\n}";
    }

    @Test public void syntaxDoesNotReportExecutedTestsWhenExecutorIsMissing() throws Exception {
        ValidationSandbox.ValidationReport report = new ValidationSandbox(null)
                .execute(true, suite(code()), "Example");
        assertTrue(report.success); // This field is the existing synthetic-validation contract.
        assertFalse(report.hasRuntimeExecution());
        assertFalse(report.getExecutionResult().wasSuccessful());
        assertTrue(report.toNarrative().contains("Prechequeo sintáctico"));
        assertTrue(report.toNarrative().contains("no fue aplicado"));
    }

    @Test public void executorFailureStaysFailureAfterSuccessfulSyntaxCheck() throws Exception {
        ValidationSandbox sandbox = new ValidationSandbox(null, (suite, target) ->
                ValidationSandbox.TestExecutionResult.create(false, "Tests failed",
                        Collections.emptyList(), "exit 7", 12));
        ValidationSandbox.ValidationReport report = sandbox.execute(true, suite(code()), "Example");
        assertTrue(report.success);
        assertTrue(report.hasRuntimeExecution());
        assertFalse(report.getExecutionResult().wasSuccessful());
        assertTrue(report.toNarrative().contains("Tests failed"));
    }

    @Test public void missingPatchOrIncompleteSuiteNeverRunsExecutor() throws Exception {
        ValidationSandbox sandbox = new ValidationSandbox(null, (suite, target) -> {
            fail("Invalid precheck must not run code"); return null;
        });
        assertFalse(sandbox.execute(false, suite(code()), "Example").success);
        assertFalse(sandbox.execute(true, suite("public class Example {}"), "Example").success);
    }
}
