package salve.core;

import android.content.Context;
import android.os.Build;
import android.text.TextUtils;
import android.util.Log;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Locale;

/**
 * Ejecuta suites de pruebas generadas por {@link AutoTestGenerator} mediante el
 * wrapper de Gradle disponible en el proyecto. Opera en modo offline y borra los
 * archivos temporales al finalizar para evitar contaminar el árbol de código.
 */
public class GradleSandboxTestExecutor implements ValidationSandbox.TestExecutor {

    private static final String TAG = "GradleSandbox";
    private static final String COVERAGE_DIR = "app/build/reports/jacoco/testDebugUnitTestReport";
    private static final String COVERAGE_FILE = "testDebugUnitTestReport.csv";
    private static final String BASELINE_DIR = ".salve/sandbox";
    private static final String BASELINE_FILE = "coverage_baseline.json";

    private final File workspaceRoot;
    private final long timeoutMillis;
    private final boolean enabled;
    private final PanelMetricasCreatividad panelMetricas;

    private GradleSandboxTestExecutor(Context context,
                                      File workspaceRoot,
                                      long timeoutMillis,
                                      boolean enabled) {
        this.workspaceRoot = workspaceRoot;
        this.timeoutMillis = timeoutMillis;
        this.enabled = enabled;
        this.panelMetricas = enabled ? new PanelMetricasCreatividad(context) : null;
    }

    public static ValidationSandbox.TestExecutor createDefault(Context context) {
        File root = discoverWorkspaceRoot(context);
        boolean available = root != null && locateGradleWrapper(root) != null;
        long timeout = Build.VERSION.SDK_INT >= Build.VERSION_CODES.O ? 90_000L : 120_000L;
        return new GradleSandboxTestExecutor(context, root, timeout, available);
    }

    private static File discoverWorkspaceRoot(Context context) {
        String hinted = System.getenv("SALVE_WORKSPACE");
        if (!TextUtils.isEmpty(hinted)) {
            File hint = new File(hinted);
            if (hint.exists()) return hint;
        }
        String current = System.getProperty("user.dir");
        if (!TextUtils.isEmpty(current)) {
            File dir = new File(current);
            if (dir.exists()) return dir;
        }
        try {
            File filesDir = context.getFilesDir();
            if (filesDir != null) {
                File parent = filesDir.getParentFile();
                if (parent != null && parent.getParentFile() != null) {
                    return parent.getParentFile();
                }
            }
        } catch (Exception ignore) { }
        return null;
    }

    private static File locateGradleWrapper(File workspace) {
        if (workspace == null) return null;
        File gradlew = new File(workspace, "gradlew");
        if (gradlew.exists()) return gradlew;
        File gradlewBat = new File(workspace, "gradlew.bat");
        return gradlewBat.exists() ? gradlewBat : null;
    }

    @Override
    public ValidationSandbox.TestExecutionResult run(AutoTestGenerator.GeneratedTestSuite suite,
                                                     String className) {
        if (!enabled || workspaceRoot == null) {
            return ValidationSandbox.TestExecutionResult.skipped(
                    "Sandbox Gradle inhabilitado en este dispositivo.");
        }
        if (suite == null || !suite.isActionable()) {
            return ValidationSandbox.TestExecutionResult.skipped(
                    "Suite no accionable; se omite la ejecución en Gradle.");
        }

        List<String> steps = new ArrayList<>();
        long start = System.currentTimeMillis();
        File testFile = null;
        String gradleOutput = "";
        boolean success = false;

        // Declaración local del guardrail (¡aquí, no en discoverWorkspaceRoot!)
        PanelMetricasCreatividad.GuardrailDecision lastGuardrail = null;

        CoverageSnapshot coverageSnapshot = null;
        try {
            File testsDir = new File(workspaceRoot,
                    "app/src/test/java/com/salve/sandbox/autogenerated");
            if (!testsDir.exists() && !testsDir.mkdirs()) {
                return ValidationSandbox.TestExecutionResult.skipped(
                        "No se pudo preparar el directorio sandbox para las pruebas.");
            }
            String suiteClassName = deriveSuiteClassName(suite);
            testFile = new File(testsDir, suiteClassName + ".java");
            writeSuite(testFile, suite.getCode());
            steps.add("Suite escrita en " + testFile.getAbsolutePath());

            File gradleWrapper = locateGradleWrapper(workspaceRoot);
            if (gradleWrapper == null) {
                steps.add("No se encontró gradlew en el workspace");
                return ValidationSandbox.TestExecutionResult.skipped(
                        "Gradle wrapper ausente; ejecución omitida.");
            }

            CommandResult result = executeGradleCommand(
                    buildCommand(gradleWrapper, suiteClassName),
                    steps,
                    "Ejecución principal");
            gradleOutput = result.output;
            if (result.timedOut) {
                return ValidationSandbox.TestExecutionResult.create(false,
                        "Timeout ejecutando gradlew test en sandbox.",
                        steps,
                        gradleOutput,
                        System.currentTimeMillis() - start);
            }
            success = result.success;

            if (success) {
                ejecutarComparativa(gradleWrapper, steps);
                coverageSnapshot = recolectarCobertura(gradleWrapper, steps);

                if (panelMetricas != null && coverageSnapshot != null) {
                    // Convertimos nuestro snapshot al tipo del panel (constructor de 6 params).
                    PanelMetricasCreatividad.CoverageSnapshot panelSnapshot =
                            new PanelMetricasCreatividad.CoverageSnapshot(
                                    coverageSnapshot.lineCoverage,
                                    coverageSnapshot.branchCoverage,
                                    coverageSnapshot.deltaLine,
                                    coverageSnapshot.deltaBranch,
                                    0.0, // campos extra requeridos por el panel
                                    0.0
                            );

                    // Evaluamos guardrails con el tipo correcto
                    PanelMetricasCreatividad.GuardrailDecision guardrail =
                            panelMetricas.evaluarGuardrailsCobertura(suite, panelSnapshot);

                    if (guardrail != null) {
                        lastGuardrail = guardrail;
                        steps.add(guardrail.toNarrative());
                        if (guardrail.blockDeployment) {
                            success = false;
                            steps.add("Guardrail: despliegue bloqueado hasta recuperar cobertura creativa.");
                        }
                        if (guardrail.sugerencias != null && !guardrail.sugerencias.isEmpty()) {
                            for (String s : guardrail.sugerencias) {
                                steps.add("Sugerencia guardrail → " + s);
                            }
                        }
                    }
                }
            }
        } catch (IOException io) {
            steps.add("Error IO: " + io.getMessage());
            gradleOutput = io.getMessage();
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            steps.add("Ejecución interrumpida: " + ie.getMessage());
            gradleOutput = ie.getMessage();
        } finally {
            if (testFile != null && testFile.exists()) {
                //noinspection ResultOfMethodCallIgnored
                testFile.delete();
            }
        }

        long duration = System.currentTimeMillis() - start;
        StringBuilder summaryBuilder = new StringBuilder(success
                ? "Suite ejecutada con éxito en sandbox offline."
                : "La ejecución del sandbox reportó fallas.");
        if (coverageSnapshot != null) {
            summaryBuilder.append(' ')
                    .append(coverageSnapshot.toSummary());
        }
        if (lastGuardrail != null && lastGuardrail.blockDeployment) {
            summaryBuilder.append(' ')
                    .append("Guardrail creativo bloqueó el despliegue hasta recuperar cobertura.");
        }
        return ValidationSandbox.TestExecutionResult.create(success,
                summaryBuilder.toString(),
                steps,
                gradleOutput,
                duration);
    }

    private String deriveSuiteClassName(AutoTestGenerator.GeneratedTestSuite suite) {
        String target = suite.getTargetClass();
        if (TextUtils.isEmpty(target)) return "GeneratedHarness";
        String sanitized = target.replaceAll("[^a-zA-Z0-9]", "");
        return sanitized + "TestHarness";
    }

    private void writeSuite(File destination, String code) throws IOException {
        try (FileWriter writer = new FileWriter(destination, false)) {
            writer.write(code);
        }
    }

    private List<String> buildCommand(File gradleWrapper, String suiteClassName) {
        String executable = gradleWrapper.getName().endsWith(".bat")
                ? gradleWrapper.getAbsolutePath()
                : "./" + gradleWrapper.getName();
        String testSelector = String.format(Locale.getDefault(),
                "com.salve.sandbox.autogenerated.%s", suiteClassName);
        List<String> args = new ArrayList<>();
        if (gradleWrapper.getName().endsWith(".bat")) {
            args.add("cmd"); args.add("/c"); args.add(executable);
        } else {
            args.add(executable);
        }
        args.addAll(Arrays.asList("test", "--offline", "--tests", testSelector));
        return args;
    }

    private void ejecutarComparativa(File gradleWrapper, List<String> steps) throws IOException, InterruptedException {
        List<String> comparativa = obtenerComandoComparativo(gradleWrapper);
        if (comparativa.isEmpty()) return;
        CommandResult result = executeGradleCommand(comparativa, steps, "Comparativa");
        if (!TextUtils.isEmpty(result.output)) {
            steps.add("Salida comparativa:\n" + acortarLog(result.output));
        }
    }

    private List<String> obtenerComandoComparativo(File gradleWrapper) {
        String raw = System.getenv("SALVE_SANDBOX_COMPARE");
        if (TextUtils.isEmpty(raw)) {
            File hints = new File(workspaceRoot, BASELINE_DIR + "/compare.cmd");
            if (hints.exists()) raw = leerArchivo(hints);
        }
        if (TextUtils.isEmpty(raw)) return Collections.emptyList();

        List<String> command = new ArrayList<>();
        if (gradleWrapper.getName().endsWith(".bat")) {
            command.add("cmd"); command.add("/c"); command.add(gradleWrapper.getAbsolutePath());
        } else {
            command.add("./" + gradleWrapper.getName());
        }
        String[] parts = raw.trim().split("\\s+");
        command.addAll(Arrays.asList(parts));
        if (!command.contains("--offline")) command.add("--offline");
        return command;
    }

    private CoverageSnapshot recolectarCobertura(File gradleWrapper, List<String> steps)
            throws IOException, InterruptedException {
        CommandResult result = executeGradleCommand(
                buildCoverageCommand(gradleWrapper),
                steps,
                "Cobertura");
        if (!result.success) {
            steps.add("No se pudieron obtener métricas de cobertura desde Gradle.");
            return null;
        }
        CoverageSnapshot snapshot = analizarCobertura();
        if (snapshot == null) {
            steps.add("No se encontró el reporte CSV de JaCoCo.");
            return null;
        }
        CoverageSnapshot baseline = cargarBaseline();
        if (baseline != null) {
            snapshot = snapshot.withDelta(baseline);
            steps.add(String.format(Locale.getDefault(),
                    "Comparativa contra baseline → Δlíneas %.2f | Δramas %.2f",
                    snapshot.deltaLine * 100,
                    snapshot.deltaBranch * 100));
        }
        guardarBaseline(snapshot);
        if (panelMetricas != null) {
            PanelMetricasCreatividad.CoverageSnapshot panelSnapshot =
                    panelMetricas.registrarCobertura(
                            snapshot.lineCoverage,
                            snapshot.branchCoverage,
                            snapshot.deltaLine,
                            snapshot.deltaBranch);
            if (panelSnapshot != null) steps.add(panelSnapshot.toNarrative());
        }
        steps.add(String.format(Locale.getDefault(),
                "Cobertura actual → líneas %.2f%% | ramas %.2f%%",
                snapshot.lineCoverage * 100,
                snapshot.branchCoverage * 100));
        return snapshot;
    }

    private List<String> buildCoverageCommand(File gradleWrapper) {
        List<String> command = new ArrayList<>();
        if (gradleWrapper.getName().endsWith(".bat")) {
            command.add("cmd"); command.add("/c"); command.add(gradleWrapper.getAbsolutePath());
        } else {
            command.add("./" + gradleWrapper.getName());
        }
        String override = System.getenv("SALVE_SANDBOX_COVERAGE_TASK");
        String tasks = TextUtils.isEmpty(override) ? "jacocoTestReport" : override.trim();
        String[] parts = tasks.split("\\s+");
        command.addAll(Arrays.asList(parts));
        if (!command.contains("--offline")) command.add("--offline");
        return command;
    }

    // Versión compatible con minSdk 24
    private CommandResult executeGradleCommand(List<String> command,
                                               List<String> steps,
                                               String etiqueta)
            throws IOException, InterruptedException {
        if (command == null || command.isEmpty()) return CommandResult.skipped();

        ProcessBuilder builder = new ProcessBuilder(command)
                .directory(workspaceRoot)
                .redirectErrorStream(true);
        builder.environment().put("GRADLE_OPTS", "-Dorg.gradle.daemon=false");

        Process process = builder.start();

        StringBuilder outputBuilder = new StringBuilder();
        Thread readerThread = new Thread(() -> {
            try (BufferedReader reader = new BufferedReader(
                    new InputStreamReader(process.getInputStream()))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    outputBuilder.append(line).append('\n');
                }
            } catch (IOException ignore) {}
        });
        readerThread.start();

        boolean finished;
        if (Build.VERSION.SDK_INT >= 26) {
            finished = process.waitFor(timeoutMillis, java.util.concurrent.TimeUnit.MILLISECONDS);
        } else {
            long start = System.currentTimeMillis();
            finished = false;
            while (true) {
                try {
                    process.exitValue();
                    finished = true;
                    break;
                } catch (IllegalThreadStateException e) {
                    if (System.currentTimeMillis() - start > timeoutMillis) break;
                    try { Thread.sleep(200); } catch (InterruptedException ie) {
                        Thread.currentThread().interrupt();
                        break;
                    }
                }
            }
        }

        if (!finished) {
            if (Build.VERSION.SDK_INT >= 26) process.destroyForcibly();
            else process.destroy();
            steps.add(etiqueta + ": timeout tras " + timeoutMillis + "ms");
            try { readerThread.join(500); } catch (InterruptedException ignore) {}
            return CommandResult.timeout(outputBuilder.toString());
        }

        int exit = process.exitValue();
        try { readerThread.join(500); } catch (InterruptedException ignore) {}
        boolean ok = exit == 0;
        steps.add(String.format(Locale.getDefault(), "%s finalizó con código %d", etiqueta, exit));
        return CommandResult.result(ok, outputBuilder.toString());
    }

    private CoverageSnapshot analizarCobertura() {
        File report = new File(workspaceRoot, COVERAGE_DIR + "/" + COVERAGE_FILE);
        if (!report.exists()) return null;

        double lineMissed = 0, lineCovered = 0, branchMissed = 0, branchCovered = 0;
        try (BufferedReader reader = new BufferedReader(new FileReader(report))) {
            String header = reader.readLine();
            if (header == null) return null;

            String[] columns = header.split(",");
            int idxLineMissed = indexOf(columns, "LINE_MISSED");
            int idxLineCovered = indexOf(columns, "LINE_COVERED");
            int idxBranchMissed = indexOf(columns, "BRANCH_MISSED");
            int idxBranchCovered = indexOf(columns, "BRANCH_COVERED");
            if (idxLineMissed < 0 || idxLineCovered < 0) return null;

            String line;
            while ((line = reader.readLine()) != null) {
                if (line.trim().isEmpty()) continue;
                String[] parts = line.split(",");
                lineMissed += safeDouble(parts, idxLineMissed);
                lineCovered += safeDouble(parts, idxLineCovered);
                branchMissed += idxBranchMissed >= 0 ? safeDouble(parts, idxBranchMissed) : 0.0;
                branchCovered += idxBranchCovered >= 0 ? safeDouble(parts, idxBranchCovered) : 0.0;
            }
        } catch (FileNotFoundException e) {
            Log.w(TAG, "Reporte de cobertura no encontrado", e);
            return null;
        } catch (IOException e) {
            Log.w(TAG, "Error leyendo reporte de cobertura", e);
            return null;
        }
        double lineTotal = lineMissed + lineCovered;
        double branchTotal = branchMissed + branchCovered;
        double lineCoverage = lineTotal == 0 ? 0 : lineCovered / lineTotal;
        double branchCoverage = branchTotal == 0 ? 0 : branchCovered / branchTotal;
        return new CoverageSnapshot(lineCoverage, branchCoverage, 0, 0);
    }

    private CoverageSnapshot cargarBaseline() {
        File baseline = new File(workspaceRoot, BASELINE_DIR + "/" + BASELINE_FILE);
        if (!baseline.exists()) return null;
        try (BufferedReader reader = new BufferedReader(new FileReader(baseline))) {
            StringBuilder builder = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) builder.append(line);
            JSONObject object = new JSONObject(builder.toString());
            return new CoverageSnapshot(
                    object.optDouble("lineCoverage", 0.0),
                    object.optDouble("branchCoverage", 0.0),
                    0,
                    0);
        } catch (IOException | JSONException e) {
            Log.w(TAG, "No se pudo cargar baseline de cobertura", e);
            return null;
        }
    }

    private void guardarBaseline(CoverageSnapshot snapshot) {
        if (snapshot == null) return;
        File dir = new File(workspaceRoot, BASELINE_DIR);
        if (!dir.exists() && !dir.mkdirs()) return;
        File baseline = new File(dir, BASELINE_FILE);
        try (FileWriter writer = new FileWriter(baseline, false)) {
            JSONObject object = new JSONObject();
            object.put("lineCoverage", snapshot.lineCoverage);
            object.put("branchCoverage", snapshot.branchCoverage);
            writer.write(object.toString());
        } catch (IOException | JSONException e) {
            Log.w(TAG, "No se pudo guardar baseline de cobertura", e);
        }
    }

    private int indexOf(String[] array, String value) {
        if (array == null || value == null) return -1;
        for (int i = 0; i < array.length; i++) if (value.equalsIgnoreCase(array[i])) return i;
        return -1;
    }

    private double safeDouble(String[] array, int index) {
        if (array == null || index < 0 || index >= array.length) return 0.0;
        try { return Double.parseDouble(array[index]); }
        catch (NumberFormatException ignore) { return 0.0; }
    }

    private String leerArchivo(File file) {
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            StringBuilder b = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) b.append(line).append(' ');
            return b.toString().trim();
        } catch (IOException e) { return null; }
    }

    private String acortarLog(String output) {
        if (TextUtils.isEmpty(output)) return "";
        return output.length() <= 800 ? output : output.substring(0, 800) + "...";
    }

    private static class CommandResult {
        final boolean success;
        final boolean timedOut;
        final String output;

        CommandResult(boolean success, boolean timedOut, String output) {
            this.success = success;
            this.timedOut = timedOut;
            this.output = output == null ? "" : output;
        }
        static CommandResult timeout(String output) { return new CommandResult(false, true, output); }
        static CommandResult result(boolean success, String output) { return new CommandResult(success, false, output); }
        static CommandResult skipped() { return new CommandResult(false, false, ""); }
    }

    private static class CoverageSnapshot {
        final double lineCoverage;
        final double branchCoverage;
        final double deltaLine;
        final double deltaBranch;

        CoverageSnapshot(double lineCoverage, double branchCoverage, double deltaLine, double deltaBranch) {
            this.lineCoverage = clamp(lineCoverage);
            this.branchCoverage = clamp(branchCoverage);
            this.deltaLine = deltaLine;
            this.deltaBranch = deltaBranch;
        }
        CoverageSnapshot withDelta(CoverageSnapshot baseline) {
            if (baseline == null) return this;
            double newDeltaLine = this.lineCoverage - baseline.lineCoverage;
            double newDeltaBranch = this.branchCoverage - baseline.branchCoverage;
            return new CoverageSnapshot(lineCoverage, branchCoverage, newDeltaLine, newDeltaBranch);
        }
        String toSummary() {
            return String.format(Locale.getDefault(),
                    "Cobertura → líneas %.2f%% (Δ %.2f) | ramas %.2f%% (Δ %.2f)",
                    lineCoverage * 100, deltaLine * 100, branchCoverage * 100, deltaBranch * 100);
        }
        private static double clamp(double v) {
            if (Double.isNaN(v)) return 0.0;
            if (v < 0.0) return 0.0;
            if (v > 1.0) return 1.0;
            return v;
        }
    }
}
