package salve.core

import android.content.Context
import android.os.Build
import android.util.Log
import org.json.JSONException
import org.json.JSONObject
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import java.io.BufferedReader
import java.io.File
import java.io.FileNotFoundException
import java.io.FileReader
import java.io.FileWriter
import java.io.IOException
import java.io.InputStreamReader
import java.util.Locale

/**
 * Ejecuta suites de pruebas generadas por [AutoTestGenerator] mediante el
 * wrapper de Gradle disponible en el proyecto. Opera en modo offline y borra los
 * archivos temporales al finalizar para evitar contaminar el árbol de código.
 */
class GradleSandboxTestExecutor private constructor(
    context: Context,
    private val workspaceRoot: File?,
    private val timeoutMillis: Long,
    private val enabled: Boolean
) : ValidationSandbox.TestExecutor {

    private val panelMetricas: PanelMetricasCreatividad? = if (enabled) {
        PanelMetricasCreatividad(context)
    } else {
        null
    }

    override fun run(
        suite: AutoTestGenerator.GeneratedTestSuite?,
        className: String?
    ): ValidationSandbox.TestExecutionResult {
        if (!enabled || workspaceRoot == null) {
            return ValidationSandbox.TestExecutionResult.skipped(
                "Sandbox Gradle inhabilitado en este dispositivo."
            )
        }
        if (suite == null || !suite.isActionable) {
            return ValidationSandbox.TestExecutionResult.skipped(
                "Suite no accionable; se omite la ejecución en Gradle."
            )
        }

        val steps = mutableListOf<String>()
        val start = System.currentTimeMillis()
        var testFile: File? = null
        var gradleOutput = ""
        var success = false
        var lastGuardrail: PanelMetricasCreatividad.GuardrailDecision? = null
        var coverageSnapshot: CoverageSnapshot? = null

        try {
            val testsDir = File(
                workspaceRoot,
                "app/src/test/java/com/salve/sandbox/autogenerated"
            )
            if (!testsDir.exists() && !testsDir.mkdirs()) {
                return ValidationSandbox.TestExecutionResult.skipped(
                    "No se pudo preparar el directorio sandbox para las pruebas."
                )
            }
            val suiteClassName = deriveSuiteClassName(suite)
            testFile = File(testsDir, "$suiteClassName.java")
            writeSuite(testFile, suite.code)
            steps.add("Suite escrita en ${testFile.absolutePath}")

            val gradleWrapper = locateGradleWrapper(workspaceRoot)
            if (gradleWrapper == null) {
                steps.add("No se encontró gradlew en el workspace")
                return ValidationSandbox.TestExecutionResult.skipped(
                    "Gradle wrapper ausente; ejecución omitida."
                )
            }

            val result = runBlocking {
                executeGradleCommand(
                    buildCommand(gradleWrapper, suiteClassName),
                    steps,
                    "Ejecución principal"
                )
            }
            gradleOutput = result.output
            if (result.timedOut) {
                return ValidationSandbox.TestExecutionResult.create(
                    false,
                    "Timeout ejecutando gradlew test en sandbox.",
                    steps,
                    gradleOutput,
                    System.currentTimeMillis() - start
                )
            }
            success = result.success

            if (success) {
                runBlocking {
                    ejecutarComparativa(gradleWrapper, steps)
                    coverageSnapshot = recolectarCobertura(gradleWrapper, steps)
                }

                if (panelMetricas != null && coverageSnapshot != null) {
                    val panelSnapshot = PanelMetricasCreatividad.CoverageSnapshot(
                        coverageSnapshot.lineCoverage,
                        coverageSnapshot.branchCoverage,
                        coverageSnapshot.deltaLine,
                        coverageSnapshot.deltaBranch,
                        0.0,
                        0.0
                    )

                    val guardrail = panelMetricas.evaluarGuardrailsCobertura(suite, panelSnapshot)
                    if (guardrail != null) {
                        lastGuardrail = guardrail
                        steps.add(guardrail.toNarrative())
                        if (guardrail.blockDeployment) {
                            success = false
                            steps.add("Guardrail: despliegue bloqueado hasta recuperar cobertura creativa.")
                        }
                        if (!guardrail.sugerencias.isNullOrEmpty()) {
                            guardrail.sugerencias.forEach { suggestion ->
                                steps.add("Sugerencia guardrail → $suggestion")
                            }
                        }
                    }
                }
            }
        } catch (io: IOException) {
            steps.add("Error IO: ${io.message}")
            gradleOutput = io.message ?: ""
        } catch (ie: InterruptedException) {
            Thread.currentThread().interrupt()
            steps.add("Ejecución interrumpida: ${ie.message}")
            gradleOutput = ie.message ?: ""
        } finally {
            testFile?.let {
                if (it.exists()) {
                    it.delete()
                }
            }
        }

        val duration = System.currentTimeMillis() - start
        val summaryBuilder = StringBuilder(
            if (success) "Suite ejecutada con éxito en sandbox offline." else "La ejecución del sandbox reportó fallas."
        )
        if (coverageSnapshot != null) {
            summaryBuilder.append(' ').append(coverageSnapshot.toSummary())
        }
        if (lastGuardrail != null) {
            summaryBuilder.append(' ').append(lastGuardrail.toNarrative())
        }

        return ValidationSandbox.TestExecutionResult.create(
            true,
            summaryBuilder.toString(),
            steps,
            gradleOutput,
            duration
        )
    }

    private fun writeSuite(file: File, content: String?) {
        if (content == null) return
        FileWriter(file, false).use { writer ->
            writer.write(content)
        }
    }

    private fun buildCommand(gradleWrapper: File, suiteClassName: String): List<String> {
        val command = mutableListOf<String>()
        if (gradleWrapper.name.endsWith(".bat")) {
            command.add("cmd")
            command.add("/c")
        }
        command.add(gradleWrapper.absolutePath)
        command.add("testDebugUnitTest")
        command.add("--tests")
        command.add("com.salve.sandbox.autogenerated.$suiteClassName")
        command.add("--no-daemon")
        command.add("--offline")
        return command
    }

    private suspend fun executeGradleCommand(
        command: List<String>,
        steps: MutableList<String>,
        label: String
    ): CommandResult {
        val process = ProcessBuilder(command)
            .directory(workspaceRoot)
            .redirectErrorStream(true)
            .start()

        val output = StringBuilder()
        val reader = BufferedReader(InputStreamReader(process.inputStream))
        val start = System.currentTimeMillis()
        var timedOut = false

        while (true) {
            while (reader.ready()) {
                output.append(reader.readLine()).append('\n')
            }
            if (!process.isAlive) {
                break
            }
            if (System.currentTimeMillis() - start > timeoutMillis) {
                timedOut = true
                process.destroy()
                break
            }
            delay(300)
        }

        val exitCode = if (timedOut) -1 else process.exitValue()
        val success = !timedOut && exitCode == 0
        steps.add("$label: ${if (success) "OK" else "FAIL"}")
        return CommandResult(success, timedOut, output.toString())
    }

    private suspend fun ejecutarComparativa(gradleWrapper: File, steps: MutableList<String>) {
        try {
            val command = buildCommand(gradleWrapper, "Comparativa")
            executeGradleCommand(command, steps, "Comparativa de baseline")
        } catch (e: Exception) {
            steps.add("Comparativa fallida: ${e.message}")
        }
    }

    private suspend fun recolectarCobertura(gradleWrapper: File, steps: MutableList<String>): CoverageSnapshot? {
        return try {
            val coverageDir = File(workspaceRoot, COVERAGE_DIR)
            val csvFile = File(coverageDir, COVERAGE_FILE)
            if (!csvFile.exists()) {
                steps.add("Cobertura: no se encontró reporte CSV.")
                return null
            }
            val snapshot = parseCoverage(csvFile)
            steps.add("Cobertura: ${snapshot.toSummary()}")
            snapshot
        } catch (e: Exception) {
            steps.add("Cobertura: error ${e.message}")
            null
        }
    }

    private fun parseCoverage(csvFile: File): CoverageSnapshot {
        val lines = csvFile.readLines()
        if (lines.size < 2) {
            return CoverageSnapshot(0.0, 0.0, 0.0, 0.0)
        }
        val data = lines[1].split(',')
        val lineCoverage = data.getOrNull(5)?.toDoubleOrNull() ?: 0.0
        val branchCoverage = data.getOrNull(7)?.toDoubleOrNull() ?: 0.0
        val baseline = readBaseline()
        val deltaLine = lineCoverage - (baseline?.lineCoverage ?: 0.0)
        val deltaBranch = branchCoverage - (baseline?.branchCoverage ?: 0.0)
        return CoverageSnapshot(lineCoverage, branchCoverage, deltaLine, deltaBranch)
    }

    private fun readBaseline(): CoverageSnapshot? {
        val baselineDir = File(workspaceRoot, BASELINE_DIR)
        val baselineFile = File(baselineDir, BASELINE_FILE)
        if (!baselineFile.exists()) {
            return null
        }
        return try {
            val json = JSONObject(baselineFile.readText())
            CoverageSnapshot(
                json.optDouble("lineCoverage", 0.0),
                json.optDouble("branchCoverage", 0.0),
                0.0,
                0.0
            )
        } catch (e: JSONException) {
            Log.w(TAG, "Error leyendo baseline: ${e.message}")
            null
        }
    }

    private fun deriveSuiteClassName(suite: AutoTestGenerator.GeneratedTestSuite): String {
        val raw = suite.primaryTestName ?: "SalveSandbox"
        return raw.replace("[^A-Za-z0-9_]".toRegex(), "")
            .ifBlank { "SalveSandbox" }
    }

    data class CoverageSnapshot(
        val lineCoverage: Double,
        val branchCoverage: Double,
        val deltaLine: Double,
        val deltaBranch: Double
    ) {
        fun toSummary(): String {
            return String.format(
                Locale.getDefault(),
                "Cobertura líneas %.2f%% (Δ %.2f), ramas %.2f%% (Δ %.2f)",
                lineCoverage,
                deltaLine,
                branchCoverage,
                deltaBranch
            )
        }
    }

    data class CommandResult(
        val success: Boolean,
        val timedOut: Boolean,
        val output: String
    )

    companion object {
        private const val TAG = "GradleSandbox"
        private const val COVERAGE_DIR = "app/build/reports/jacoco/testDebugUnitTestReport"
        private const val COVERAGE_FILE = "testDebugUnitTestReport.csv"
        private const val BASELINE_DIR = ".salve/sandbox"
        private const val BASELINE_FILE = "coverage_baseline.json"

        @JvmStatic
        fun createDefault(context: Context): ValidationSandbox.TestExecutor {
            val root = discoverWorkspaceRoot(context)
            val available = root != null && locateGradleWrapper(root) != null
            val timeout = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) 90_000L else 120_000L
            return GradleSandboxTestExecutor(context, root, timeout, available)
        }

        private fun discoverWorkspaceRoot(context: Context): File? {
            val hinted = System.getenv("SALVE_WORKSPACE")
            if (!hinted.isNullOrEmpty()) {
                val hint = File(hinted)
                if (hint.exists()) return hint
            }
            val current = System.getProperty("user.dir")
            if (!current.isNullOrEmpty()) {
                val dir = File(current)
                if (dir.exists()) return dir
            }
            return try {
                val filesDir = context.filesDir
                val parent = filesDir?.parentFile?.parentFile
                if (parent != null && parent.exists()) parent else null
            } catch (e: Exception) {
                null
            }
        }

        private fun locateGradleWrapper(workspace: File?): File? {
            if (workspace == null) return null
            val gradlew = File(workspace, "gradlew")
            if (gradlew.exists()) return gradlew
            val gradlewBat = File(workspace, "gradlew.bat")
            return if (gradlewBat.exists()) gradlewBat else null
        }
    }
}
