package salve.avatar;
import org.junit.Test;
import static org.junit.Assert.*;
import static salve.avatar.ArticulatedPose.Joint.*;
public class ArticulatedPoseTest {
 @Test public void allPresetsRoundTrip(){for(ArticulatedPose.Preset id:ArticulatedPose.Preset.values()){ArticulatedPose p=ArticulatedPose.preset(id);assertEquals(p.toJson(),ArticulatedPose.fromJson(p.toJson()).toJson());}}
 @Test public void rejectMalformedPersistence(){String valid=new ArticulatedPose().toJson();String[] bad={null,"{}",valid+"{}",valid.replace("\"version\":1","\"version\":2"),valid.replace("\"TORSO\":0.0","\"TORSO\":0,\"TORSO\":0"),valid.replace("\"HEAD\":0.0","\"HEAD\":100"),valid.replace("\"HEAD\":0.0","\"HEAD\":\"0\""),valid.replace("\"HEAD\":0.0","\"HEAD\":1e999"),valid.replace("\"HEAD\":0.0","\"UNKNOWN\":0"),valid.replace(",\"HEAD\":0.0","")};for(String s:bad)assertThrows(IllegalArgumentException.class,()->ArticulatedPose.fromJson(s));}
 @Test public void posesAreImmutableAndBounded(){ArticulatedPose p=new ArticulatedPose();assertEquals(0,p.angle(HEAD),0);p.with(HEAD,10);assertEquals(0,p.angle(HEAD),0);for(float f:new float[]{Float.NaN,Float.POSITIVE_INFINITY,23,-23})assertThrows(IllegalArgumentException.class,()->p.with(HEAD,f));}
 @Test public void transitionsStayWithinLimits(){for(ArticulatedPose.Preset a:ArticulatedPose.Preset.values())for(ArticulatedPose.Preset b:ArticulatedPose.Preset.values())for(int i=0;i<=100;i++){ArticulatedPose p=ArticulatedPose.interpolate(ArticulatedPose.preset(a),ArticulatedPose.preset(b),i/100f);for(ArticulatedPose.Joint j:ArticulatedPose.Joint.values())assertTrue(p.angle(j)>=j.min-.001&&p.angle(j)<=j.max+.001);}}
 @Test public void interpolationHonorsEndpoints(){ArticulatedPose a=new ArticulatedPose(),b=ArticulatedPose.preset(ArticulatedPose.Preset.GREETING);assertEquals(a.toJson(),ArticulatedPose.interpolate(a,b,-1).toJson());assertEquals(b.toJson(),ArticulatedPose.interpolate(a,b,2).toJson());}
 @Test public void parentAndChildSharePivot(){for(ArticulatedPose.Preset id:ArticulatedPose.Preset.values()){ArticulatedRig.Frame f=new ArticulatedRig.Frame(ArticulatedPose.preset(id).with(TORSO,15));same(f.leftUpper,f.leftForearm,310,630);same(f.rightUpper,f.rightForearm,645,630);same(f.leftThigh,f.leftCalf,410,1190);same(f.rightThigh,f.rightCalf,567,1190);same(f.torso,f.leftUpper,363,444);same(f.torso,f.head,479,390);}}
 private void same(ArticulatedRig.Transform a,ArticulatedRig.Transform b,float x,float y){assertEquals(a.x(x,y),b.x(x,y),.001);assertEquals(a.y(x,y),b.y(x,y),.001);}
 @Test public void neutralSkinningPreservesCoordinates(){ArticulatedRig.Frame f=new ArticulatedRig.Frame(new ArticulatedPose());float[] out=new float[2];for(ArticulatedRig.Part part:ArticulatedRig.Part.values()){f.point(part,421,642,out,0);assertEquals(421,out[0],.001);assertEquals(642,out[1],.001);}}
 @Test public void skinningIsContinuousAtBlendBoundaries(){float[] a=new float[2],b=new float[2];ArticulatedRig.Frame f=new ArticulatedRig.Frame(ArticulatedPose.preset(ArticulatedPose.Preset.ELBOWS_BENT));for(float y:new float[]{565,695}){f.point(ArticulatedRig.Part.LEFT_ARM,310,y-.001f,a,0);f.point(ArticulatedRig.Part.LEFT_ARM,310,y+.001f,b,0);assertTrue(Math.hypot(a[0]-b[0],a[1]-b[1])<.01);}}
 @Test public void floorReferenceIsStable(){for(ArticulatedPose.Preset id:ArticulatedPose.Preset.values()){ArticulatedRig.Frame f=new ArticulatedRig.Frame(ArticulatedPose.preset(id));assertEquals(1536,Math.max(f.leftCalf.y(390,1536),f.rightCalf.y(610,1536))+f.groundOffset,.001);}}
}
